### ISSUE TITLE
Data processing - Đang

### ISSUE THREAD

**Issue by LongVu219** [dangnq2501/INT2208#1]
- tách từ, lọc kí tự, normalize ctct,......
- cho qua 1 mô hình word embedd

@dangnq2501

**Comment by LongVu219** [comment]
check this note book : https://colab.research.google.com/drive/1KPA_MGvGHhvyhvAGVH0AKdkGVIuMJrqs?usp=sharing&fbclid=IwAR0AA_3QYoIqCKS5YpwN1TNs5nY9zeyk4-h5nYxlDspUve4rwkuiXU7J7Nk

**Comment by dangnq2501** [comment]
- My data preprocessing:https://colab.research.google.com/drive/1v1chCBecHWiLW9IHX3u1BrbzfNU7--f8?usp=drive_link
- My data analysis: https://colab.research.google.com/drive/1ryVnzY9aweApiFQ-28bkA_m9kTNlpx2s?usp=sharing

**Comment by LongVu219** [comment]
- Resize each post to 500, 700 merged word, 1/2 head, 1/2 tail (n2)
- Use 100dim-model, 300dim model (n1)
- total 4 dataset
- final output : csv file contain n1*n2 matrix and label


- rememberto fix auto-label
